---
# tasks file for db
- name: Import MongoDB public GPG Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: D68FA50FEA312927
  tags: install

- name: Add MongoDB repository into sources list
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install MongoDB package
  apt:
    name: mongodb-org
    update_cache: yes
  tags: install

- name: Enable mongo
  service: name=mongod enabled=yes
