---
  - name: Deploy Puma
    hosts: reddit_app
    become: true

    tasks:
    - name: Show info about the env this host belongs to
      debug:
        msg: 'This host is in {{ env }} environment!!!'

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: "/home/{{ deploy_user }}/db_config"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
      tags: install

    - name: Add unit file for Puma
      template:
        src: puma.service.j2
        dest: /etc/systemd/system/puma.service
      notify: start puma

    - name: enable puma
      systemd: name=puma enabled=yes
