---
  - name: Deploy Puma
    hosts: reddit_app
    become: true

    tasks:
      - name: Fetch the latest version of application code
        git:
          repo: 'https://github.com/express42/reddit.git'
          dest: /home/appuser/reddit
          version: monolith

      - name: Ruby install
        apt:
          pkg:
          - ruby-full
          - ruby-bundler
          - build-essential

      - name: Bundle install
        bundler:
          state: present
          chdir: /home/appuser/reddit
