plugin: 'gcp_compute'
regions: 'europe-west1'
projects: 'infra-271122'
service_account_file: 'service_account.json'
auth_kind: 'serviceaccount'
hostnames: 'name'
keyed_groups:
  - key: 'zone'
groups:
  stage: "'stage' in name"
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
