Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
    #v.gui = false
    #v.customize [ "modifyvm", :id, "--uartmode1", "disconnected"]
    #v.customize [ "modifyvm", :id, "--nested-hw-virt", "off"]
    #v.customize [ "modifyvm", :id, "--nestedpaging", "off"]
    #v.customize [ "modifyvm", :id, "--hwvirtex", "off"]
    v.customize [ "modifyvm", :id, "--audio", "none"]
  end

  config.vm.define "dbserver" do |db|
    #db.vm.boot_timeout = 1200
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"
    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "reddit_db" => ["dbserver"],
      "reddit_db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
      }
    end
  end

  config.vm.define "appserver" do |app|
    #app.vm.boot_timeout = 1200
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "reddit_app" => ["appserver"],
      "reddit_app:vars" => { "db_host" => "10.10.10.10"}
      }
      ansible.extra_vars = {
        "deploy_user" => "ubuntu"
      }
    end
  end
end
